services:
  - type: web
    name: smart-grid-energy-api
    env: python
    pythonVersion: 3.11.6
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
